/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequisicoesRouteImport } from './routes/requisicoes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EstoqueOperacionalRouteImport } from './routes/estoque-operacional'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisaoSugestoesRouteImport } from './routes/visao.sugestoes'
import { Route as VisaoPlanoAcaoRouteImport } from './routes/visao.plano-acao'
import { Route as VisaoObservacoesRouteImport } from './routes/visao.observacoes'
import { Route as VendasPlanejamentoRouteImport } from './routes/vendas.planejamento'
import { Route as VendasPedidosRouteImport } from './routes/vendas.pedidos'
import { Route as VendasIndicadoresRouteImport } from './routes/vendas.indicadores'
import { Route as VendasDisponibilidadeRouteImport } from './routes/vendas.disponibilidade'
import { Route as VendasCrmB2cRouteImport } from './routes/vendas.crm-b2c'
import { Route as VendasCrmB2bRouteImport } from './routes/vendas.crm-b2b'
import { Route as VendasAnaliseVendedoresRouteImport } from './routes/vendas.analise-vendedores'
import { Route as ProducaoSopRouteImport } from './routes/producao.sop'
import { Route as ProducaoProgramacaoRouteImport } from './routes/producao.programacao'
import { Route as ProducaoOrdensRouteImport } from './routes/producao.ordens'
import { Route as ProducaoManutencaoRouteImport } from './routes/producao.manutencao'
import { Route as ProducaoIndicadoresRouteImport } from './routes/producao.indicadores'
import { Route as ProducaoGargalosRouteImport } from './routes/producao.gargalos'
import { Route as ProducaoConsumoRouteImport } from './routes/producao.consumo'
import { Route as InteligenciaRelatoriosRouteImport } from './routes/inteligencia.relatorios'
import { Route as InteligenciaHistoricoRouteImport } from './routes/inteligencia.historico'
import { Route as EstoqueVencimentosRouteImport } from './routes/estoque.vencimentos'
import { Route as EstoqueRecebimentosRouteImport } from './routes/estoque.recebimentos'
import { Route as EstoqueInventarioRouteImport } from './routes/estoque.inventario'
import { Route as EstoqueIndicadoresRouteImport } from './routes/estoque.indicadores'
import { Route as EstoqueDevolucoesRouteImport } from './routes/estoque.devolucoes'
import { Route as ComprasIndicadoresRouteImport } from './routes/compras.indicadores'
import { Route as ComprasFichasRouteImport } from './routes/compras.fichas'
import { Route as ComprasAcordosRouteImport } from './routes/compras.acordos'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AdminLimpezaRouteImport } from './routes/admin.limpeza'
import { Route as AdminIndicadoresRouteImport } from './routes/admin.indicadores'
import { Route as AdminEscritorioRouteImport } from './routes/admin.escritorio'
import { Route as AdminEpiRouteImport } from './routes/admin.epi'

const RequisicoesRoute = RequisicoesRouteImport.update({
  id: '/requisicoes',
  path: '/requisicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueOperacionalRoute = EstoqueOperacionalRouteImport.update({
  id: '/estoque-operacional',
  path: '/estoque-operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoSugestoesRoute = VisaoSugestoesRouteImport.update({
  id: '/visao/sugestoes',
  path: '/visao/sugestoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoPlanoAcaoRoute = VisaoPlanoAcaoRouteImport.update({
  id: '/visao/plano-acao',
  path: '/visao/plano-acao',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaoObservacoesRoute = VisaoObservacoesRouteImport.update({
  id: '/visao/observacoes',
  path: '/visao/observacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasPlanejamentoRoute = VendasPlanejamentoRouteImport.update({
  id: '/vendas/planejamento',
  path: '/vendas/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasPedidosRoute = VendasPedidosRouteImport.update({
  id: '/vendas/pedidos',
  path: '/vendas/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasIndicadoresRoute = VendasIndicadoresRouteImport.update({
  id: '/vendas/indicadores',
  path: '/vendas/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasDisponibilidadeRoute = VendasDisponibilidadeRouteImport.update({
  id: '/vendas/disponibilidade',
  path: '/vendas/disponibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasCrmB2cRoute = VendasCrmB2cRouteImport.update({
  id: '/vendas/crm-b2c',
  path: '/vendas/crm-b2c',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasCrmB2bRoute = VendasCrmB2bRouteImport.update({
  id: '/vendas/crm-b2b',
  path: '/vendas/crm-b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasAnaliseVendedoresRoute = VendasAnaliseVendedoresRouteImport.update({
  id: '/vendas/analise-vendedores',
  path: '/vendas/analise-vendedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoSopRoute = ProducaoSopRouteImport.update({
  id: '/producao/sop',
  path: '/producao/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoProgramacaoRoute = ProducaoProgramacaoRouteImport.update({
  id: '/producao/programacao',
  path: '/producao/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoOrdensRoute = ProducaoOrdensRouteImport.update({
  id: '/producao/ordens',
  path: '/producao/ordens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoManutencaoRoute = ProducaoManutencaoRouteImport.update({
  id: '/producao/manutencao',
  path: '/producao/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoIndicadoresRoute = ProducaoIndicadoresRouteImport.update({
  id: '/producao/indicadores',
  path: '/producao/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoGargalosRoute = ProducaoGargalosRouteImport.update({
  id: '/producao/gargalos',
  path: '/producao/gargalos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoConsumoRoute = ProducaoConsumoRouteImport.update({
  id: '/producao/consumo',
  path: '/producao/consumo',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRelatoriosRoute = InteligenciaRelatoriosRouteImport.update({
  id: '/inteligencia/relatorios',
  path: '/inteligencia/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaHistoricoRoute = InteligenciaHistoricoRouteImport.update({
  id: '/inteligencia/historico',
  path: '/inteligencia/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueVencimentosRoute = EstoqueVencimentosRouteImport.update({
  id: '/vencimentos',
  path: '/vencimentos',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueRecebimentosRoute = EstoqueRecebimentosRouteImport.update({
  id: '/recebimentos',
  path: '/recebimentos',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueInventarioRoute = EstoqueInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueIndicadoresRoute = EstoqueIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueDevolucoesRoute = EstoqueDevolucoesRouteImport.update({
  id: '/devolucoes',
  path: '/devolucoes',
  getParentRoute: () => EstoqueRoute,
} as any)
const ComprasIndicadoresRoute = ComprasIndicadoresRouteImport.update({
  id: '/compras/indicadores',
  path: '/compras/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasFichasRoute = ComprasFichasRouteImport.update({
  id: '/compras/fichas',
  path: '/compras/fichas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasAcordosRoute = ComprasAcordosRouteImport.update({
  id: '/compras/acordos',
  path: '/compras/acordos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/admin/solicitacoes',
  path: '/admin/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLimpezaRoute = AdminLimpezaRouteImport.update({
  id: '/admin/limpeza',
  path: '/admin/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndicadoresRoute = AdminIndicadoresRouteImport.update({
  id: '/admin/indicadores',
  path: '/admin/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEscritorioRoute = AdminEscritorioRouteImport.update({
  id: '/admin/escritorio',
  path: '/admin/escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEpiRoute = AdminEpiRouteImport.update({
  id: '/admin/epi',
  path: '/admin/epi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/estoque-operacional': typeof EstoqueOperacionalRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/pedidos': typeof PedidosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/produtos': typeof ProdutosRoute
  '/requisicoes': typeof RequisicoesRoute
  '/admin/epi': typeof AdminEpiRoute
  '/admin/escritorio': typeof AdminEscritorioRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/limpeza': typeof AdminLimpezaRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/compras/acordos': typeof ComprasAcordosRoute
  '/compras/fichas': typeof ComprasFichasRoute
  '/compras/indicadores': typeof ComprasIndicadoresRoute
  '/estoque/devolucoes': typeof EstoqueDevolucoesRoute
  '/estoque/indicadores': typeof EstoqueIndicadoresRoute
  '/estoque/inventario': typeof EstoqueInventarioRoute
  '/estoque/recebimentos': typeof EstoqueRecebimentosRoute
  '/estoque/vencimentos': typeof EstoqueVencimentosRoute
  '/inteligencia/historico': typeof InteligenciaHistoricoRoute
  '/inteligencia/relatorios': typeof InteligenciaRelatoriosRoute
  '/producao/consumo': typeof ProducaoConsumoRoute
  '/producao/gargalos': typeof ProducaoGargalosRoute
  '/producao/indicadores': typeof ProducaoIndicadoresRoute
  '/producao/manutencao': typeof ProducaoManutencaoRoute
  '/producao/ordens': typeof ProducaoOrdensRoute
  '/producao/programacao': typeof ProducaoProgramacaoRoute
  '/producao/sop': typeof ProducaoSopRoute
  '/vendas/analise-vendedores': typeof VendasAnaliseVendedoresRoute
  '/vendas/crm-b2b': typeof VendasCrmB2bRoute
  '/vendas/crm-b2c': typeof VendasCrmB2cRoute
  '/vendas/disponibilidade': typeof VendasDisponibilidadeRoute
  '/vendas/indicadores': typeof VendasIndicadoresRoute
  '/vendas/pedidos': typeof VendasPedidosRoute
  '/vendas/planejamento': typeof VendasPlanejamentoRoute
  '/visao/observacoes': typeof VisaoObservacoesRoute
  '/visao/plano-acao': typeof VisaoPlanoAcaoRoute
  '/visao/sugestoes': typeof VisaoSugestoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/estoque-operacional': typeof EstoqueOperacionalRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/pedidos': typeof PedidosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/produtos': typeof ProdutosRoute
  '/requisicoes': typeof RequisicoesRoute
  '/admin/epi': typeof AdminEpiRoute
  '/admin/escritorio': typeof AdminEscritorioRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/limpeza': typeof AdminLimpezaRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/compras/acordos': typeof ComprasAcordosRoute
  '/compras/fichas': typeof ComprasFichasRoute
  '/compras/indicadores': typeof ComprasIndicadoresRoute
  '/estoque/devolucoes': typeof EstoqueDevolucoesRoute
  '/estoque/indicadores': typeof EstoqueIndicadoresRoute
  '/estoque/inventario': typeof EstoqueInventarioRoute
  '/estoque/recebimentos': typeof EstoqueRecebimentosRoute
  '/estoque/vencimentos': typeof EstoqueVencimentosRoute
  '/inteligencia/historico': typeof InteligenciaHistoricoRoute
  '/inteligencia/relatorios': typeof InteligenciaRelatoriosRoute
  '/producao/consumo': typeof ProducaoConsumoRoute
  '/producao/gargalos': typeof ProducaoGargalosRoute
  '/producao/indicadores': typeof ProducaoIndicadoresRoute
  '/producao/manutencao': typeof ProducaoManutencaoRoute
  '/producao/ordens': typeof ProducaoOrdensRoute
  '/producao/programacao': typeof ProducaoProgramacaoRoute
  '/producao/sop': typeof ProducaoSopRoute
  '/vendas/analise-vendedores': typeof VendasAnaliseVendedoresRoute
  '/vendas/crm-b2b': typeof VendasCrmB2bRoute
  '/vendas/crm-b2c': typeof VendasCrmB2cRoute
  '/vendas/disponibilidade': typeof VendasDisponibilidadeRoute
  '/vendas/indicadores': typeof VendasIndicadoresRoute
  '/vendas/pedidos': typeof VendasPedidosRoute
  '/vendas/planejamento': typeof VendasPlanejamentoRoute
  '/visao/observacoes': typeof VisaoObservacoesRoute
  '/visao/plano-acao': typeof VisaoPlanoAcaoRoute
  '/visao/sugestoes': typeof VisaoSugestoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/estoque-operacional': typeof EstoqueOperacionalRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/pedidos': typeof PedidosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/produtos': typeof ProdutosRoute
  '/requisicoes': typeof RequisicoesRoute
  '/admin/epi': typeof AdminEpiRoute
  '/admin/escritorio': typeof AdminEscritorioRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/limpeza': typeof AdminLimpezaRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/compras/acordos': typeof ComprasAcordosRoute
  '/compras/fichas': typeof ComprasFichasRoute
  '/compras/indicadores': typeof ComprasIndicadoresRoute
  '/estoque/devolucoes': typeof EstoqueDevolucoesRoute
  '/estoque/indicadores': typeof EstoqueIndicadoresRoute
  '/estoque/inventario': typeof EstoqueInventarioRoute
  '/estoque/recebimentos': typeof EstoqueRecebimentosRoute
  '/estoque/vencimentos': typeof EstoqueVencimentosRoute
  '/inteligencia/historico': typeof InteligenciaHistoricoRoute
  '/inteligencia/relatorios': typeof InteligenciaRelatoriosRoute
  '/producao/consumo': typeof ProducaoConsumoRoute
  '/producao/gargalos': typeof ProducaoGargalosRoute
  '/producao/indicadores': typeof ProducaoIndicadoresRoute
  '/producao/manutencao': typeof ProducaoManutencaoRoute
  '/producao/ordens': typeof ProducaoOrdensRoute
  '/producao/programacao': typeof ProducaoProgramacaoRoute
  '/producao/sop': typeof ProducaoSopRoute
  '/vendas/analise-vendedores': typeof VendasAnaliseVendedoresRoute
  '/vendas/crm-b2b': typeof VendasCrmB2bRoute
  '/vendas/crm-b2c': typeof VendasCrmB2cRoute
  '/vendas/disponibilidade': typeof VendasDisponibilidadeRoute
  '/vendas/indicadores': typeof VendasIndicadoresRoute
  '/vendas/pedidos': typeof VendasPedidosRoute
  '/vendas/planejamento': typeof VendasPlanejamentoRoute
  '/visao/observacoes': typeof VisaoObservacoesRoute
  '/visao/plano-acao': typeof VisaoPlanoAcaoRoute
  '/visao/sugestoes': typeof VisaoSugestoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/cotacoes'
    | '/estoque'
    | '/estoque-operacional'
    | '/fornecedores'
    | '/indicadores'
    | '/movimentacoes'
    | '/pedidos'
    | '/planejamento'
    | '/produtos'
    | '/requisicoes'
    | '/admin/epi'
    | '/admin/escritorio'
    | '/admin/indicadores'
    | '/admin/limpeza'
    | '/admin/solicitacoes'
    | '/compras/acordos'
    | '/compras/fichas'
    | '/compras/indicadores'
    | '/estoque/devolucoes'
    | '/estoque/indicadores'
    | '/estoque/inventario'
    | '/estoque/recebimentos'
    | '/estoque/vencimentos'
    | '/inteligencia/historico'
    | '/inteligencia/relatorios'
    | '/producao/consumo'
    | '/producao/gargalos'
    | '/producao/indicadores'
    | '/producao/manutencao'
    | '/producao/ordens'
    | '/producao/programacao'
    | '/producao/sop'
    | '/vendas/analise-vendedores'
    | '/vendas/crm-b2b'
    | '/vendas/crm-b2c'
    | '/vendas/disponibilidade'
    | '/vendas/indicadores'
    | '/vendas/pedidos'
    | '/vendas/planejamento'
    | '/visao/observacoes'
    | '/visao/plano-acao'
    | '/visao/sugestoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/cotacoes'
    | '/estoque'
    | '/estoque-operacional'
    | '/fornecedores'
    | '/indicadores'
    | '/movimentacoes'
    | '/pedidos'
    | '/planejamento'
    | '/produtos'
    | '/requisicoes'
    | '/admin/epi'
    | '/admin/escritorio'
    | '/admin/indicadores'
    | '/admin/limpeza'
    | '/admin/solicitacoes'
    | '/compras/acordos'
    | '/compras/fichas'
    | '/compras/indicadores'
    | '/estoque/devolucoes'
    | '/estoque/indicadores'
    | '/estoque/inventario'
    | '/estoque/recebimentos'
    | '/estoque/vencimentos'
    | '/inteligencia/historico'
    | '/inteligencia/relatorios'
    | '/producao/consumo'
    | '/producao/gargalos'
    | '/producao/indicadores'
    | '/producao/manutencao'
    | '/producao/ordens'
    | '/producao/programacao'
    | '/producao/sop'
    | '/vendas/analise-vendedores'
    | '/vendas/crm-b2b'
    | '/vendas/crm-b2c'
    | '/vendas/disponibilidade'
    | '/vendas/indicadores'
    | '/vendas/pedidos'
    | '/vendas/planejamento'
    | '/visao/observacoes'
    | '/visao/plano-acao'
    | '/visao/sugestoes'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/cotacoes'
    | '/estoque'
    | '/estoque-operacional'
    | '/fornecedores'
    | '/indicadores'
    | '/movimentacoes'
    | '/pedidos'
    | '/planejamento'
    | '/produtos'
    | '/requisicoes'
    | '/admin/epi'
    | '/admin/escritorio'
    | '/admin/indicadores'
    | '/admin/limpeza'
    | '/admin/solicitacoes'
    | '/compras/acordos'
    | '/compras/fichas'
    | '/compras/indicadores'
    | '/estoque/devolucoes'
    | '/estoque/indicadores'
    | '/estoque/inventario'
    | '/estoque/recebimentos'
    | '/estoque/vencimentos'
    | '/inteligencia/historico'
    | '/inteligencia/relatorios'
    | '/producao/consumo'
    | '/producao/gargalos'
    | '/producao/indicadores'
    | '/producao/manutencao'
    | '/producao/ordens'
    | '/producao/programacao'
    | '/producao/sop'
    | '/vendas/analise-vendedores'
    | '/vendas/crm-b2b'
    | '/vendas/crm-b2c'
    | '/vendas/disponibilidade'
    | '/vendas/indicadores'
    | '/vendas/pedidos'
    | '/vendas/planejamento'
    | '/visao/observacoes'
    | '/visao/plano-acao'
    | '/visao/sugestoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CotacoesRoute: typeof CotacoesRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  EstoqueOperacionalRoute: typeof EstoqueOperacionalRoute
  FornecedoresRoute: typeof FornecedoresRoute
  IndicadoresRoute: typeof IndicadoresRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  PedidosRoute: typeof PedidosRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  ProdutosRoute: typeof ProdutosRoute
  RequisicoesRoute: typeof RequisicoesRoute
  AdminEpiRoute: typeof AdminEpiRoute
  AdminEscritorioRoute: typeof AdminEscritorioRoute
  AdminIndicadoresRoute: typeof AdminIndicadoresRoute
  AdminLimpezaRoute: typeof AdminLimpezaRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  ComprasAcordosRoute: typeof ComprasAcordosRoute
  ComprasFichasRoute: typeof ComprasFichasRoute
  ComprasIndicadoresRoute: typeof ComprasIndicadoresRoute
  InteligenciaHistoricoRoute: typeof InteligenciaHistoricoRoute
  InteligenciaRelatoriosRoute: typeof InteligenciaRelatoriosRoute
  ProducaoConsumoRoute: typeof ProducaoConsumoRoute
  ProducaoGargalosRoute: typeof ProducaoGargalosRoute
  ProducaoIndicadoresRoute: typeof ProducaoIndicadoresRoute
  ProducaoManutencaoRoute: typeof ProducaoManutencaoRoute
  ProducaoOrdensRoute: typeof ProducaoOrdensRoute
  ProducaoProgramacaoRoute: typeof ProducaoProgramacaoRoute
  ProducaoSopRoute: typeof ProducaoSopRoute
  VendasAnaliseVendedoresRoute: typeof VendasAnaliseVendedoresRoute
  VendasCrmB2bRoute: typeof VendasCrmB2bRoute
  VendasCrmB2cRoute: typeof VendasCrmB2cRoute
  VendasDisponibilidadeRoute: typeof VendasDisponibilidadeRoute
  VendasIndicadoresRoute: typeof VendasIndicadoresRoute
  VendasPedidosRoute: typeof VendasPedidosRoute
  VendasPlanejamentoRoute: typeof VendasPlanejamentoRoute
  VisaoObservacoesRoute: typeof VisaoObservacoesRoute
  VisaoPlanoAcaoRoute: typeof VisaoPlanoAcaoRoute
  VisaoSugestoesRoute: typeof VisaoSugestoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requisicoes': {
      id: '/requisicoes'
      path: '/requisicoes'
      fullPath: '/requisicoes'
      preLoaderRoute: typeof RequisicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-operacional': {
      id: '/estoque-operacional'
      path: '/estoque-operacional'
      fullPath: '/estoque-operacional'
      preLoaderRoute: typeof EstoqueOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao/sugestoes': {
      id: '/visao/sugestoes'
      path: '/visao/sugestoes'
      fullPath: '/visao/sugestoes'
      preLoaderRoute: typeof VisaoSugestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao/plano-acao': {
      id: '/visao/plano-acao'
      path: '/visao/plano-acao'
      fullPath: '/visao/plano-acao'
      preLoaderRoute: typeof VisaoPlanoAcaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visao/observacoes': {
      id: '/visao/observacoes'
      path: '/visao/observacoes'
      fullPath: '/visao/observacoes'
      preLoaderRoute: typeof VisaoObservacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/planejamento': {
      id: '/vendas/planejamento'
      path: '/vendas/planejamento'
      fullPath: '/vendas/planejamento'
      preLoaderRoute: typeof VendasPlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/pedidos': {
      id: '/vendas/pedidos'
      path: '/vendas/pedidos'
      fullPath: '/vendas/pedidos'
      preLoaderRoute: typeof VendasPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/indicadores': {
      id: '/vendas/indicadores'
      path: '/vendas/indicadores'
      fullPath: '/vendas/indicadores'
      preLoaderRoute: typeof VendasIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/disponibilidade': {
      id: '/vendas/disponibilidade'
      path: '/vendas/disponibilidade'
      fullPath: '/vendas/disponibilidade'
      preLoaderRoute: typeof VendasDisponibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/crm-b2c': {
      id: '/vendas/crm-b2c'
      path: '/vendas/crm-b2c'
      fullPath: '/vendas/crm-b2c'
      preLoaderRoute: typeof VendasCrmB2cRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/crm-b2b': {
      id: '/vendas/crm-b2b'
      path: '/vendas/crm-b2b'
      fullPath: '/vendas/crm-b2b'
      preLoaderRoute: typeof VendasCrmB2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/analise-vendedores': {
      id: '/vendas/analise-vendedores'
      path: '/vendas/analise-vendedores'
      fullPath: '/vendas/analise-vendedores'
      preLoaderRoute: typeof VendasAnaliseVendedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/sop': {
      id: '/producao/sop'
      path: '/producao/sop'
      fullPath: '/producao/sop'
      preLoaderRoute: typeof ProducaoSopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/programacao': {
      id: '/producao/programacao'
      path: '/producao/programacao'
      fullPath: '/producao/programacao'
      preLoaderRoute: typeof ProducaoProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/ordens': {
      id: '/producao/ordens'
      path: '/producao/ordens'
      fullPath: '/producao/ordens'
      preLoaderRoute: typeof ProducaoOrdensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/manutencao': {
      id: '/producao/manutencao'
      path: '/producao/manutencao'
      fullPath: '/producao/manutencao'
      preLoaderRoute: typeof ProducaoManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/indicadores': {
      id: '/producao/indicadores'
      path: '/producao/indicadores'
      fullPath: '/producao/indicadores'
      preLoaderRoute: typeof ProducaoIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/gargalos': {
      id: '/producao/gargalos'
      path: '/producao/gargalos'
      fullPath: '/producao/gargalos'
      preLoaderRoute: typeof ProducaoGargalosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao/consumo': {
      id: '/producao/consumo'
      path: '/producao/consumo'
      fullPath: '/producao/consumo'
      preLoaderRoute: typeof ProducaoConsumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia/relatorios': {
      id: '/inteligencia/relatorios'
      path: '/inteligencia/relatorios'
      fullPath: '/inteligencia/relatorios'
      preLoaderRoute: typeof InteligenciaRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia/historico': {
      id: '/inteligencia/historico'
      path: '/inteligencia/historico'
      fullPath: '/inteligencia/historico'
      preLoaderRoute: typeof InteligenciaHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/vencimentos': {
      id: '/estoque/vencimentos'
      path: '/vencimentos'
      fullPath: '/estoque/vencimentos'
      preLoaderRoute: typeof EstoqueVencimentosRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/recebimentos': {
      id: '/estoque/recebimentos'
      path: '/recebimentos'
      fullPath: '/estoque/recebimentos'
      preLoaderRoute: typeof EstoqueRecebimentosRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/inventario': {
      id: '/estoque/inventario'
      path: '/inventario'
      fullPath: '/estoque/inventario'
      preLoaderRoute: typeof EstoqueInventarioRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/indicadores': {
      id: '/estoque/indicadores'
      path: '/indicadores'
      fullPath: '/estoque/indicadores'
      preLoaderRoute: typeof EstoqueIndicadoresRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/devolucoes': {
      id: '/estoque/devolucoes'
      path: '/devolucoes'
      fullPath: '/estoque/devolucoes'
      preLoaderRoute: typeof EstoqueDevolucoesRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/compras/indicadores': {
      id: '/compras/indicadores'
      path: '/compras/indicadores'
      fullPath: '/compras/indicadores'
      preLoaderRoute: typeof ComprasIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/fichas': {
      id: '/compras/fichas'
      path: '/compras/fichas'
      fullPath: '/compras/fichas'
      preLoaderRoute: typeof ComprasFichasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/acordos': {
      id: '/compras/acordos'
      path: '/compras/acordos'
      fullPath: '/compras/acordos'
      preLoaderRoute: typeof ComprasAcordosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/admin/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/limpeza': {
      id: '/admin/limpeza'
      path: '/admin/limpeza'
      fullPath: '/admin/limpeza'
      preLoaderRoute: typeof AdminLimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/indicadores': {
      id: '/admin/indicadores'
      path: '/admin/indicadores'
      fullPath: '/admin/indicadores'
      preLoaderRoute: typeof AdminIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/escritorio': {
      id: '/admin/escritorio'
      path: '/admin/escritorio'
      fullPath: '/admin/escritorio'
      preLoaderRoute: typeof AdminEscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/epi': {
      id: '/admin/epi'
      path: '/admin/epi'
      fullPath: '/admin/epi'
      preLoaderRoute: typeof AdminEpiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EstoqueRouteChildren {
  EstoqueDevolucoesRoute: typeof EstoqueDevolucoesRoute
  EstoqueIndicadoresRoute: typeof EstoqueIndicadoresRoute
  EstoqueInventarioRoute: typeof EstoqueInventarioRoute
  EstoqueRecebimentosRoute: typeof EstoqueRecebimentosRoute
  EstoqueVencimentosRoute: typeof EstoqueVencimentosRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueDevolucoesRoute: EstoqueDevolucoesRoute,
  EstoqueIndicadoresRoute: EstoqueIndicadoresRoute,
  EstoqueInventarioRoute: EstoqueInventarioRoute,
  EstoqueRecebimentosRoute: EstoqueRecebimentosRoute,
  EstoqueVencimentosRoute: EstoqueVencimentosRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CotacoesRoute: CotacoesRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  EstoqueOperacionalRoute: EstoqueOperacionalRoute,
  FornecedoresRoute: FornecedoresRoute,
  IndicadoresRoute: IndicadoresRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  PedidosRoute: PedidosRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  ProdutosRoute: ProdutosRoute,
  RequisicoesRoute: RequisicoesRoute,
  AdminEpiRoute: AdminEpiRoute,
  AdminEscritorioRoute: AdminEscritorioRoute,
  AdminIndicadoresRoute: AdminIndicadoresRoute,
  AdminLimpezaRoute: AdminLimpezaRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  ComprasAcordosRoute: ComprasAcordosRoute,
  ComprasFichasRoute: ComprasFichasRoute,
  ComprasIndicadoresRoute: ComprasIndicadoresRoute,
  InteligenciaHistoricoRoute: InteligenciaHistoricoRoute,
  InteligenciaRelatoriosRoute: InteligenciaRelatoriosRoute,
  ProducaoConsumoRoute: ProducaoConsumoRoute,
  ProducaoGargalosRoute: ProducaoGargalosRoute,
  ProducaoIndicadoresRoute: ProducaoIndicadoresRoute,
  ProducaoManutencaoRoute: ProducaoManutencaoRoute,
  ProducaoOrdensRoute: ProducaoOrdensRoute,
  ProducaoProgramacaoRoute: ProducaoProgramacaoRoute,
  ProducaoSopRoute: ProducaoSopRoute,
  VendasAnaliseVendedoresRoute: VendasAnaliseVendedoresRoute,
  VendasCrmB2bRoute: VendasCrmB2bRoute,
  VendasCrmB2cRoute: VendasCrmB2cRoute,
  VendasDisponibilidadeRoute: VendasDisponibilidadeRoute,
  VendasIndicadoresRoute: VendasIndicadoresRoute,
  VendasPedidosRoute: VendasPedidosRoute,
  VendasPlanejamentoRoute: VendasPlanejamentoRoute,
  VisaoObservacoesRoute: VisaoObservacoesRoute,
  VisaoPlanoAcaoRoute: VisaoPlanoAcaoRoute,
  VisaoSugestoesRoute: VisaoSugestoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
