/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitacoesRouteImport } from './routes/solicitacoes'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'

const SolicitacoesRoute = SolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/solicitacoes': typeof SolicitacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/solicitacoes': typeof SolicitacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/solicitacoes': typeof SolicitacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/cotacoes'
    | '/estoque'
    | '/fornecedores'
    | '/indicadores'
    | '/pedidos'
    | '/produtos'
    | '/solicitacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/cotacoes'
    | '/estoque'
    | '/fornecedores'
    | '/indicadores'
    | '/pedidos'
    | '/produtos'
    | '/solicitacoes'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/cotacoes'
    | '/estoque'
    | '/fornecedores'
    | '/indicadores'
    | '/pedidos'
    | '/produtos'
    | '/solicitacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  CotacoesRoute: typeof CotacoesRoute
  EstoqueRoute: typeof EstoqueRoute
  FornecedoresRoute: typeof FornecedoresRoute
  IndicadoresRoute: typeof IndicadoresRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  SolicitacoesRoute: typeof SolicitacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitacoes': {
      id: '/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof SolicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  CotacoesRoute: CotacoesRoute,
  EstoqueRoute: EstoqueRoute,
  FornecedoresRoute: FornecedoresRoute,
  IndicadoresRoute: IndicadoresRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  SolicitacoesRoute: SolicitacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
