/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequisicoesRouteImport } from './routes/requisicoes'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EstoqueOperacionalRouteImport } from './routes/estoque-operacional'
import { Route as CotacoesRouteImport } from './routes/cotacoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'

const RequisicoesRoute = RequisicoesRouteImport.update({
  id: '/requisicoes',
  path: '/requisicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueOperacionalRoute = EstoqueOperacionalRouteImport.update({
  id: '/estoque-operacional',
  path: '/estoque-operacional',
  getParentRoute: () => rootRouteImport,
} as any)
const CotacoesRoute = CotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque-operacional': typeof EstoqueOperacionalRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/requisicoes': typeof RequisicoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque-operacional': typeof EstoqueOperacionalRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/requisicoes': typeof RequisicoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/cotacoes': typeof CotacoesRoute
  '/estoque-operacional': typeof EstoqueOperacionalRoute
  '/estoque': typeof EstoqueRoute
  '/fornecedores': typeof FornecedoresRoute
  '/indicadores': typeof IndicadoresRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/planejamento': typeof PlanejamentoRoute
  '/requisicoes': typeof RequisicoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/cotacoes'
    | '/estoque-operacional'
    | '/estoque'
    | '/fornecedores'
    | '/indicadores'
    | '/movimentacoes'
    | '/pedidos'
    | '/produtos'
    | '/planejamento'
    | '/requisicoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/cotacoes'
    | '/estoque-operacional'
    | '/estoque'
    | '/fornecedores'
    | '/indicadores'
    | '/movimentacoes'
    | '/pedidos'
    | '/produtos'
    | '/planejamento'
    | '/requisicoes'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/configuracoes'
    | '/cotacoes'
    | '/estoque-operacional'
    | '/estoque'
    | '/fornecedores'
    | '/indicadores'
    | '/movimentacoes'
    | '/pedidos'
    | '/produtos'
    | '/planejamento'
    | '/requisicoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CotacoesRoute: typeof CotacoesRoute
  EstoqueOperacionalRoute: typeof EstoqueOperacionalRoute
  EstoqueRoute: typeof EstoqueRoute
  FornecedoresRoute: typeof FornecedoresRoute
  IndicadoresRoute: typeof IndicadoresRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RequisicoesRoute: typeof RequisicoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/requisicoes': {
      id: '/requisicoes'
      path: '/requisicoes'
      fullPath: '/requisicoes'
      preLoaderRoute: typeof RequisicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque-operacional': {
      id: '/estoque-operacional'
      path: '/estoque-operacional'
      fullPath: '/estoque-operacional'
      preLoaderRoute: typeof EstoqueOperacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotacoes': {
      id: '/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof CotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CotacoesRoute: CotacoesRoute,
  EstoqueOperacionalRoute: EstoqueOperacionalRoute,
  EstoqueRoute: EstoqueRoute,
  FornecedoresRoute: FornecedoresRoute,
  IndicadoresRoute: IndicadoresRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RequisicoesRoute: RequisicoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
